### PR TITLE
use Java 7, dependency cleanup, use generics

### PR DESCRIPTION
**Pull request by madness-inc**

### CODE REVIEW

**Comment by arimus** [comment]
Sorry for the delay in responding to this. I like the changes, my only concern is folks still using jmimemagic with Java < 1.7. Yes, there are plenty of those folks out there, but I'm uncertain how many of them are using jmimemagic. We could always push forward and if enough folks have an issue, we could create a 1.6 compatible branch.

**Comment by madness-inc** [comment]
Hi arimus,
nice to hear from you.
Well, if it's only about the source level, we could easily replace the diamond operators <> with the correct inferred type arguments. Then we'd be compatible to 1.6, too.

Regards
Matthias

**Comment by arimus** [comment]
Yeah, I'm good with that. If we can target 1.6, that keeps backward compatibility for now. I've actually had a lot of these types of changes staged for a couple years, but I keep getting pulled off in other directions. Thanks for the nudge.

I should really dig some of my other changes out of the graveyard as well, which included support for JSON configuration files and additional mime types.

**Comment by arimus** [comment]
Looks like a clean merge and tests pass.

**Comment by madness-inc** [comment]
Hi,

thank you for merging this.
Do you plan to release the new version soon?

Regards
Matthias

**Comment by arimus** [comment]
I'll try to get a new build done this upcoming week. Feel free to ping me
again if you don't see it go out. I'll update this ticket when I do.

**Comment by arimus** [comment]
Give it a whirl:

http://repo1.maven.org/maven2/net/sf/jmimemagic/jmimemagic/0.1.5/

**Comment by madness-inc** [comment]
Great, tnx!

**Pull request merged**
